import {
  checkOutlier,
  checkTimedOutlier,
  findSpec,
  isTimedMeasure,
  lineKey,
  MAX_METRES,
  MAX_SECONDS,
  proposeForMeasure,
  type ExerciseSpec,
  type GymFingerprint,
  type HistorySession,
  type LineIdentity,
  type LoggedSet,
  type Measure,
  type OutlierResult,
  type OutlierStatus,
  type Proposal,
  type RejectionMemory,
  type SetupType,
} from "@gain/engine";
import type { Db, Deps } from "./driver";

export interface SetRow {
  id: string;
  sessionId: string;
  exerciseId: string;
  lineId: string;
  position: number;
  load: number;
  /** 1 for a timed or distance set (one hold / one carry). */
  reps: number;
  /** Seconds held (time exercises), else null. */
  durationS: number | null;
  /** Metres carried (distance exercises), else null. */
  distanceM: number | null;
  rir: number | null;
  warmup: boolean;
  tags: string[];
  outlierStatus: OutlierStatus;
  createdAt: number;
}

export interface LogSetInput {
  /** Pre-generated by the UI per draft so a double tap can never insert the same set twice. */
  id?: string;
  sessionId: string;
  exerciseId: string;
  load: number;
  /** Ignored for time and distance exercises (stored as 1). */
  reps: number;
  /** Required for a time exercise: whole seconds, 1..3600. */
  durationS?: number | null;
  /** Required for a distance exercise: metres, above 0 and up to 5000. */
  distanceM?: number | null;
  rir?: number | null;
  warmup?: boolean;
  tags?: string[];
}

export interface DayExerciseSpec {
  exerciseId: string;
  equipment: ExerciseSpec["equipment"];
  setup: SetupType;
  /** How the exercise is counted; omitted = reps. For time / distance, repMin..repMax is the seconds / metres range. */
  measure?: Measure;
  repMin: number;
  repMax: number;
  /** Exercise name (for the default ceiling by name). */
  name?: string;
  /** The resolved rep ceiling for this lift (per-lift edit, else the default for its kind). Omitted = the engine's default by name. */
  repCeiling?: number;
  isGoalLift: boolean;
  trackEffort: boolean;
  sets: number;
}

type RawSet = {
  id: string;
  session_id: string;
  exercise_id: string;
  line_id: string;
  position: number;
  load: number;
  reps: number;
  duration_s: number | null;
  distance_m: number | null;
  rir: number | null;
  is_warmup: number;
  tags_json: string;
  outlier_status: OutlierStatus;
  created_at: number;
};

const toSetRow = (r: RawSet): SetRow => ({
  id: r.id,
  sessionId: r.session_id,
  exerciseId: r.exercise_id,
  lineId: r.line_id,
  position: r.position,
  load: r.load,
  reps: r.reps,
  durationS: r.duration_s,
  distanceM: r.distance_m,
  rir: r.rir,
  warmup: r.is_warmup === 1,
  tags: JSON.parse(r.tags_json) as string[],
  outlierStatus: r.outlier_status,
  createdAt: r.created_at,
});

const toLogged = (r: SetRow): LoggedSet => ({
  load: r.load,
  reps: r.reps,
  ...(r.durationS !== null ? { durationS: r.durationS } : {}),
  ...(r.distanceM !== null ? { distanceM: r.distanceM } : {}),
  rir: r.rir,
  warmup: r.warmup,
  tags: r.tags,
  outlierStatus: r.outlierStatus,
});

/** Today's changes to one programme slot of an open workout. */
export interface ExerciseState {
  /** The programme exercise this slot comes from. */
  slot: string;
  removed: boolean;
  /** Exercise swapped in for today only; null = the programme's own exercise. */
  replacedBy: string | null;
  note: string;
  /** The lifter turned the automatic rest timer off for this exercise. */
  restOff: boolean;
  /** An exercise added to today's workout that is not in the programme day (then `slot` is the exercise's own id). */
  added: boolean;
  /** Order among the added exercises (1, 2, ...); null for programme slots. */
  position: number | null;
  /** Exercises with the same group value are a superset. Null = not in one. */
  superset: string | null;
}

export class ExerciseAlreadyInWorkout extends Error {
  constructor() {
    super("This exercise is already part of today's workout");
  }
}

export class ExerciseHasSets extends Error {
  constructor() {
    super("Delete the sets logged for this exercise before replacing it");
  }
}

export function createWorkoutRepo(db: Db, deps: Deps) {
  const { newId, now } = deps;

  /** Resume the open session for this programme day if there is one, otherwise create it. Never creates a second one. */
  async function startOrResumeSession(dayId: string, gymId: string): Promise<{ id: string; resumed: boolean }> {
    const find = () =>
      db.get<{ id: string; status: string }>(
        "SELECT id, status FROM session WHERE programme_day_id = ? AND status IN ('planned','in_progress') AND deleted_at IS NULL",
        [dayId],
      );
    return db.transaction(async () => {
      const open = await find();
      const t = now();
      if (open) {
        if (open.status === "planned") {
          await db.run("UPDATE session SET status = 'in_progress', started_at = ?, updated_at = ? WHERE id = ?", [t, t, open.id]);
        }
        return { id: open.id, resumed: true };
      }
      const day = await db.get<{ programme_version_id: string }>("SELECT programme_version_id FROM programme_day WHERE id = ? AND deleted_at IS NULL", [dayId]);
      if (!day) throw new Error("Unknown programme day");
      const id = newId();
      await db.run(
        `INSERT INTO session (id, programme_version_id, programme_day_id, gym_id, status, started_at, created_at, updated_at)
         VALUES (?, ?, ?, ?, 'in_progress', ?, ?, ?)`,
        [id, day.programme_version_id, dayId, gymId, t, t, t],
      );
      return { id, resumed: false };
    });
  }

  /** The workout that is open right now (at most one), so Today can offer "resume" instead of starting another day. */
  async function getOpenSession(): Promise<{ id: string; dayId: string } | null> {
    const r = await db.get<{ id: string; programme_day_id: string }>("SELECT id, programme_day_id FROM session WHERE status = 'in_progress' AND deleted_at IS NULL ORDER BY started_at DESC LIMIT 1");
    return r ? { id: r.id, dayId: r.programme_day_id } : null;
  }

  async function getSession(sessionId: string) {
    return db.get<{ id: string; programme_day_id: string; gym_id: string; status: string; started_at: number | null; finished_at: number | null }>(
      "SELECT id, programme_day_id, gym_id, status, started_at, finished_at FROM session WHERE id = ? AND deleted_at IS NULL",
      [sessionId],
    );
  }

  async function finishSession(sessionId: string): Promise<void> {
    const t = now();
    await db.run("UPDATE session SET status = 'finished', finished_at = ?, updated_at = ? WHERE id = ? AND status = 'in_progress'", [t, t, sessionId]);
  }

  async function getLine(exerciseId: string, gymId: string, setup: SetupType): Promise<{ id: string } | null> {
    return db.get<{ id: string }>(
      "SELECT id FROM exercise_line WHERE exercise_id = ? AND gym_id = ? AND setup = ? AND deleted_at IS NULL",
      [exerciseId, gymId, setup],
    );
  }

  /** A line is created on first use (e.g. a new gym or a new setup starts a separate history stream). */
  async function ensureLine(exerciseId: string, gymId: string, setup: SetupType): Promise<string> {
    const existing = await getLine(exerciseId, gymId, setup);
    if (existing) return existing.id;
    const id = newId();
    const t = now();
    await db.run("INSERT INTO exercise_line (id, exercise_id, gym_id, setup, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?)", [id, exerciseId, gymId, setup, t, t]);
    return id;
  }

  async function listSessionSets(sessionId: string, exerciseId?: string): Promise<SetRow[]> {
    const rows = await db.all<RawSet>(
      `SELECT id, session_id, exercise_id, line_id, position, load, reps, duration_s, distance_m, rir, is_warmup, tags_json, outlier_status, created_at
       FROM workout_set WHERE session_id = ? AND deleted_at IS NULL ${exerciseId ? "AND exercise_id = ?" : ""}
       ORDER BY exercise_id, position`,
      exerciseId ? [sessionId, exerciseId] : [sessionId],
    );
    return rows.map(toSetRow);
  }

  /** Finished sessions of one line, oldest first, as engine history. Unconfirmed outliers are kept (the engine ignores them). */
  async function getHistory(line: LineIdentity, lineId: string): Promise<HistorySession[]> {
    const rows = await db.all<RawSet & { sid: string; finished_at: number }>(
      `SELECT ws.*, s.id AS sid, s.finished_at AS finished_at FROM workout_set ws JOIN session s ON s.id = ws.session_id
       WHERE ws.line_id = ? AND s.status = 'finished' AND ws.deleted_at IS NULL AND s.deleted_at IS NULL
       ORDER BY s.finished_at, ws.position`,
      [lineId],
    );
    const bySession = new Map<string, HistorySession>();
    for (const r of rows) {
      let h = bySession.get(r.sid);
      if (!h) {
        h = { line, performedAt: new Date(r.finished_at).toISOString(), sets: [] };
        bySession.set(r.sid, h);
      }
      h.sets.push(toLogged(toSetRow(r)));
    }
    return [...bySession.values()];
  }

  /** The last finished session of this line: what the lifter did last time, for display. */
  async function lastPerformance(line: LineIdentity, lineId: string): Promise<{ performedAt: string; sets: LoggedSet[] } | null> {
    const h = await getHistory(line, lineId);
    const last = h[h.length - 1];
    // Working sets only: no warm-ups and no drop sets, so row N of today lines up with working set N of last time.
    return last ? { performedAt: last.performedAt, sets: last.sets.filter((s) => !s.warmup && !s.tags?.includes("drop")) } : null;
  }

  async function loadRejectionMemory(line: LineIdentity, lineId: string): Promise<RejectionMemory> {
    const rows = await db.all<{ jump_kind: string; count: number; last_rejected_at: number }>(
      "SELECT jump_kind, count, last_rejected_at FROM rejection_memory WHERE line_id = ? AND deleted_at IS NULL",
      [lineId],
    );
    const key = lineKey(line);
    return { records: rows.map((r) => ({ lineKey: key, jumpKind: r.jump_kind, count: r.count, lastRejectedAt: new Date(r.last_rejected_at).toISOString() })) };
  }

  /** Engine proposal for one programme exercise from history that exists right now. Not stored (PR5 stores the next session's). */
  async function liveProposal(ex: DayExerciseSpec, gym: GymFingerprint): Promise<{ proposal: Proposal; lineId: string; line: LineIdentity }> {
    const line: LineIdentity = { exerciseId: ex.exerciseId, gymId: gym.gymId, setup: ex.setup };
    const lineId = await ensureLine(ex.exerciseId, gym.gymId, ex.setup);
    const history = await getHistory(line, lineId);
    const rejections = await loadRejectionMemory(line, lineId);
    const proposal = proposeForMeasure({
      exercise: {
        exerciseId: ex.exerciseId,
        name: ex.name,
        measure: ex.measure,
        equipment: ex.equipment,
        setup: ex.setup,
        repRange: { min: ex.repMin, max: ex.repMax },
        progression: ex.repCeiling !== undefined && !isTimedMeasure(ex.measure) ? { repCeiling: ex.repCeiling } : undefined,
        isGoalLift: ex.isGoalLift,
        trackEffort: ex.trackEffort,
        plannedSets: ex.sets,
      },
      gym,
      history,
      rejections,
      asOf: new Date(now()).toISOString(),
    });
    return { proposal, lineId, line };
  }

  /** How an exercise is counted. Unknown ids count in reps (the caller's own checks refuse them). */
  async function measureOf(exerciseId: string): Promise<Measure> {
    const r = await db.get<{ measure: Measure }>("SELECT measure FROM exercise WHERE id = ?", [exerciseId]);
    return r?.measure ?? "reps";
  }

  /** The seconds / metres a set must carry for this measure; throws on anything else. Reps exercises store neither. */
  function checkQuantity(measure: Measure, durationS: number | null | undefined, distanceM: number | null | undefined): { durationS: number | null; distanceM: number | null } {
    if (measure === "time") {
      if (typeof durationS !== "number" || !Number.isInteger(durationS) || durationS < 1 || durationS > MAX_SECONDS) throw new Error("Invalid set");
      return { durationS, distanceM: null };
    }
    if (measure === "distance") {
      if (typeof distanceM !== "number" || !Number.isFinite(distanceM) || distanceM <= 0 || distanceM > MAX_METRES) throw new Error("Invalid set");
      return { durationS: null, distanceM };
    }
    return { durationS: null, distanceM: null };
  }

  /**
   * Save a set locally and check it against the recent line. A set far from the line is stored as `unconfirmed`
   * and does not move the next target until the lifter confirms it. Warm-ups are never checked.
   * Idempotent on `id`: a double tap with the same draft id inserts once.
   */
  async function logSet(
    input: LogSetInput,
    ctx: { gym: GymFingerprint; equipment: ExerciseSpec["equipment"]; setup: SetupType },
  ): Promise<{ id: string; created: boolean; outlier: OutlierResult | null }> {
    const id = input.id ?? newId();
    const existing = await db.get<{ id: string }>("SELECT id FROM workout_set WHERE id = ?", [id]);
    if (existing) return { id, created: false, outlier: null };
    const session = await getSession(input.sessionId);
    if (!session) throw new Error("Unknown session");
    if (session.status !== "in_progress") throw new Error("Session is not in progress");
    const measure = await measureOf(input.exerciseId);
    const q = checkQuantity(measure, input.durationS, input.distanceM);
    if ((measure === "reps" && !(input.reps >= 1)) || !Number.isFinite(input.load) || input.load < 0) throw new Error("Invalid set");
    const lineId = await ensureLine(input.exerciseId, session.gym_id, ctx.setup);
    const line: LineIdentity = { exerciseId: input.exerciseId, gymId: session.gym_id, setup: ctx.setup };

    // Warm-ups and drop sets are lighter on purpose, so they are never compared with the line.
    let outlier: OutlierResult | null = null;
    if (!input.warmup && !input.tags?.includes("drop")) {
      const history = await getHistory(line, lineId);
      const todaySets = (await listSessionSets(input.sessionId, input.exerciseId)).map(toLogged);
      if (todaySets.length > 0) history.push({ line, performedAt: new Date(now()).toISOString(), sets: todaySets });
      outlier = isTimedMeasure(measure)
        ? checkTimedOutlier({ load: input.load, reps: 1, durationS: q.durationS, distanceM: q.distanceM }, measure, { line, history })
        : checkOutlier({ load: input.load, reps: input.reps, rir: input.rir ?? null }, { line, history, gymSpec: findSpec(ctx.gym, ctx.equipment) });
    }
    const t = now();
    const pos = await db.get<{ p: number | null }>("SELECT MAX(position) AS p FROM workout_set WHERE session_id = ? AND exercise_id = ?", [input.sessionId, input.exerciseId]);
    await db.run(
      `INSERT INTO workout_set (id, session_id, exercise_id, line_id, position, load, reps, duration_s, distance_m, rir, is_warmup, tags_json, outlier_status, created_at, updated_at)
       VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
      [id, input.sessionId, input.exerciseId, lineId, (pos?.p ?? 0) + 1, input.load, measure === "reps" ? input.reps : 1, q.durationS, q.distanceM, measure === "reps" ? input.rir ?? null : null, input.warmup ? 1 : 0, JSON.stringify(input.tags ?? []), outlier?.outlierStatus ?? "none", t, t],
    );
    return { id, created: true, outlier };
  }

  /**
   * Log a planned warm-up ladder as warm-up sets. Ids are fixed per session, exercise and step, so a double tap or a
   * retry after a crash adds nothing twice. Warm-ups skip the outlier check and never drive progression.
   */
  async function addWarmups(
    sessionId: string,
    exerciseId: string,
    steps: { load: number; reps: number }[],
    ctx: { gym: GymFingerprint; equipment: ExerciseSpec["equipment"]; setup: SetupType },
  ): Promise<number> {
    let added = 0;
    for (const [i, s] of steps.entries()) {
      const r = await logSet({ id: `${sessionId}:${exerciseId}:wu${i}`, sessionId, exerciseId, load: s.load, reps: s.reps, warmup: true }, ctx);
      if (r.created) added++;
    }
    return added;
  }

  async function setOutlierStatus(setId: string, status: Exclude<OutlierStatus, "none">): Promise<void> {
    const t = now();
    // "rejected" means: not right (typo / wrong plate). It is excluded from every calculation and hidden.
    await db.run("UPDATE workout_set SET outlier_status = ?, updated_at = ?, deleted_at = CASE WHEN ? = 'rejected' THEN ? ELSE deleted_at END WHERE id = ?", [status, t, status, t, setId]);
  }

  /**
   * Correct a set of the workout that is still open (typed over in the list). The outlier check runs again against the other sets;
   * a set the lifter already confirmed stays confirmed when its numbers did not change.
   */
  async function updateLiveSet(
    setId: string,
    v: { load: number; reps: number; rir: number | null; warmup: boolean; tags?: string[]; durationS?: number | null; distanceM?: number | null },
    ctx: { gym: GymFingerprint; equipment: ExerciseSpec["equipment"]; setup: SetupType },
  ): Promise<{ outlier: OutlierResult | null }> {
    const row = await db.get<{ session_id: string; exercise_id: string; line_id: string; load: number; reps: number; duration_s: number | null; distance_m: number | null; outlier_status: OutlierStatus; gym_id: string }>(
      `SELECT ws.session_id, ws.exercise_id, ws.line_id, ws.load, ws.reps, ws.duration_s, ws.distance_m, ws.outlier_status, s.gym_id AS gym_id FROM workout_set ws JOIN session s ON s.id = ws.session_id
       WHERE ws.id = ? AND ws.deleted_at IS NULL AND s.status = 'in_progress'`,
      [setId],
    );
    if (!row) throw new Error("Unknown set");
    const measure = await measureOf(row.exercise_id);
    const q = checkQuantity(measure, v.durationS, v.distanceM);
    const reps = measure === "reps" ? v.reps : 1;
    if (!(reps >= 1) || !Number.isFinite(v.load) || v.load < 0) throw new Error("Invalid set");
    let outlier: OutlierResult | null = null;
    let status: OutlierStatus = "none";
    if (!v.warmup && !v.tags?.includes("drop")) {
      const line: LineIdentity = { exerciseId: row.exercise_id, gymId: row.gym_id, setup: ctx.setup };
      const history = await getHistory(line, row.line_id);
      const others = (await listSessionSets(row.session_id, row.exercise_id)).filter((x) => x.id !== setId).map(toLogged);
      if (others.length > 0) history.push({ line, performedAt: new Date(now()).toISOString(), sets: others });
      outlier = isTimedMeasure(measure)
        ? checkTimedOutlier({ load: v.load, reps: 1, durationS: q.durationS, distanceM: q.distanceM }, measure, { line, history })
        : checkOutlier({ load: v.load, reps, rir: v.rir }, { line, history, gymSpec: findSpec(ctx.gym, ctx.equipment) });
      const unchanged = row.load === v.load && row.reps === reps && row.duration_s === q.durationS && row.distance_m === q.distanceM;
      status = row.outlier_status === "confirmed" && unchanged ? "confirmed" : outlier.outlierStatus;
    }
    const tagsJson = v.tags === undefined ? null : JSON.stringify(v.tags);
    await db.run("UPDATE workout_set SET load = ?, reps = ?, duration_s = ?, distance_m = ?, rir = ?, is_warmup = ?, tags_json = COALESCE(?, tags_json), outlier_status = ?, updated_at = ? WHERE id = ?", [v.load, reps, q.durationS, q.distanceM, measure === "reps" ? v.rir : null, v.warmup ? 1 : 0, tagsJson, status, now(), setId]);
    return { outlier };
  }

  async function deleteSet(setId: string): Promise<void> {
    const t = now();
    await db.run("UPDATE workout_set SET deleted_at = ?, updated_at = ? WHERE id = ? AND deleted_at IS NULL", [t, t, setId]);
  }

  // ---- per-workout changes to a programme slot (remove / replace / note / rest timer) ----------------------
  async function listExerciseState(sessionId: string): Promise<ExerciseState[]> {
    const rows = await db.all<{ slot_exercise_id: string; removed: number; replaced_by: string | null; note: string | null; rest_off: number; added: number; position: number | null; superset_group: string | null }>(
      "SELECT slot_exercise_id, removed, replaced_by, note, rest_off, added, position, superset_group FROM session_exercise WHERE session_id = ? AND deleted_at IS NULL ORDER BY position, created_at",
      [sessionId],
    );
    return rows.map((r) => ({ slot: r.slot_exercise_id, removed: r.removed === 1, replacedBy: r.replaced_by, note: r.note ?? "", restOff: r.rest_off === 1, added: r.added === 1, position: r.position, superset: r.superset_group }));
  }

  async function patchExerciseState(sessionId: string, slot: string, patch: Partial<Omit<ExerciseState, "slot">>): Promise<void> {
    const t = now();
    const cur = await db.get<{ id: string }>("SELECT id FROM session_exercise WHERE session_id = ? AND slot_exercise_id = ? AND deleted_at IS NULL", [sessionId, slot]);
    if (!cur) {
      await db.run(
        "INSERT INTO session_exercise (id, session_id, slot_exercise_id, removed, replaced_by, note, rest_off, added, position, superset_group, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)",
        [newId(), sessionId, slot, patch.removed ? 1 : 0, patch.replacedBy ?? null, patch.note ?? null, patch.restOff ? 1 : 0, patch.added ? 1 : 0, patch.position ?? null, patch.superset ?? null, t, t],
      );
      return;
    }
    const sets: string[] = [];
    const args: (string | number | null)[] = [];
    if (patch.removed !== undefined) (sets.push("removed = ?"), args.push(patch.removed ? 1 : 0));
    if (patch.replacedBy !== undefined) (sets.push("replaced_by = ?"), args.push(patch.replacedBy));
    if (patch.note !== undefined) (sets.push("note = ?"), args.push(patch.note));
    if (patch.restOff !== undefined) (sets.push("rest_off = ?"), args.push(patch.restOff ? 1 : 0));
    if (patch.added !== undefined) (sets.push("added = ?"), args.push(patch.added ? 1 : 0));
    if (patch.position !== undefined) (sets.push("position = ?"), args.push(patch.position));
    if (patch.superset !== undefined) (sets.push("superset_group = ?"), args.push(patch.superset));
    if (sets.length === 0) return;
    await db.run(`UPDATE session_exercise SET ${sets.join(", ")}, updated_at = ? WHERE id = ?`, [...args, t, cur.id]);
  }

  /** Delete every logged set of one exercise in this workout (soft delete). Returns how many. */
  async function clearExerciseSets(sessionId: string, exerciseId: string): Promise<number> {
    const t = now();
    const rows = await listSessionSets(sessionId, exerciseId);
    for (const r of rows) await db.run("UPDATE workout_set SET deleted_at = ?, updated_at = ? WHERE id = ? AND deleted_at IS NULL", [t, t, r.id]);
    return rows.length;
  }

  /**
   * Take an exercise out of today's workout. Sets already logged for it are deleted (the caller asks first), so a removed exercise leaves
   * nothing behind in history or in the next targets. The programme is untouched; restoring brings the exercise back (empty).
   */
  async function removeExercise(sessionId: string, slot: string, displayExerciseId: string): Promise<void> {
    await db.transaction(async () => {
      await clearExerciseSets(sessionId, displayExerciseId);
      await patchExerciseState(sessionId, slot, { removed: true });
    });
  }

  /** Swap a slot for another exercise for today only. Refused once sets are logged for the current one (remove those first). */
  async function replaceExercise(sessionId: string, slot: string, currentExerciseId: string, withExerciseId: string | null): Promise<void> {
    const logged = await listSessionSets(sessionId, currentExerciseId);
    if (logged.length > 0) throw new ExerciseHasSets();
    if (withExerciseId && (await listExerciseState(sessionId)).some((s) => s.added && s.slot === withExerciseId)) throw new ExerciseAlreadyInWorkout();
    await patchExerciseState(sessionId, slot, { replacedBy: withExerciseId, removed: false });
  }

  /**
   * Add an exercise to today's workout that is not in the programme day. Nothing about the programme changes and it gets no next-session
   * target (targets are written per programme exercise); its sets count in history and the finish summary like any other. An exercise that is
   * already part of the workout (in the day, swapped in, or added earlier) is refused; one the lifter removed earlier is put back.
   */
  async function addExercise(sessionId: string, exerciseId: string): Promise<{ restored: boolean }> {
    const session = await getSession(sessionId);
    if (!session || session.status !== "in_progress") throw new Error("Session is not in progress");
    const ex = await db.get<{ id: string }>("SELECT id FROM exercise WHERE id = ? AND deleted_at IS NULL", [exerciseId]);
    if (!ex) throw new Error("Unknown exercise");
    return db.transaction(async () => {
      const states = await listExerciseState(sessionId);
      const inDay = await db.get<{ id: string }>("SELECT id FROM programme_day_exercise WHERE programme_day_id = ? AND exercise_id = ? AND deleted_at IS NULL", [session.programme_day_id, exerciseId]);
      const mine = states.find((s) => s.slot === exerciseId);
      if (mine?.added) {
        if (!mine.removed) throw new ExerciseAlreadyInWorkout();
        await patchExerciseState(sessionId, exerciseId, { removed: false });
        return { restored: true };
      }
      // In the programme day (shown, swapped away or removed: "Put back" handles those) or swapped in for another slot: never twice.
      if (inDay || states.some((s) => s.replacedBy === exerciseId)) throw new ExerciseAlreadyInWorkout();
      const pos = (states.reduce((m, s) => Math.max(m, s.position ?? 0), 0)) + 1;
      await patchExerciseState(sessionId, exerciseId, { added: true, position: pos });
      return { restored: false };
    });
  }

  /** Put exercises of this workout into one superset (same group), or take them out (group null). Only changes today's display and rest timer. */
  async function setSuperset(sessionId: string, groups: Record<string, string | null>): Promise<void> {
    await db.transaction(async () => {
      for (const [slot, group] of Object.entries(groups)) await patchExerciseState(sessionId, slot, { superset: group });
    });
  }

  return {
    addExercise,
    setSuperset,
    listExerciseState,
    patchExerciseState,
    clearExerciseSets,
    removeExercise,
    replaceExercise,
    startOrResumeSession,
    getOpenSession,
    getSession,
    finishSession,
    getLine,
    ensureLine,
    listSessionSets,
    getHistory,
    lastPerformance,
    loadRejectionMemory,
    liveProposal,
    logSet,
    addWarmups,
    setOutlierStatus,
    updateLiveSet,
    deleteSet,
  };
}
export type WorkoutRepo = ReturnType<typeof createWorkoutRepo>;
