import {
  checkOutlier,
  findSpec,
  lineKey,
  proposeNext,
  type ExerciseSpec,
  type GymFingerprint,
  type HistorySession,
  type LineIdentity,
  type LoggedSet,
  type OutlierResult,
  type OutlierStatus,
  type Proposal,
  type RejectionMemory,
  type SetupType,
} from "@gain/engine";
import type { Db, Deps } from "./driver";

export interface SetRow {
  id: string;
  sessionId: string;
  exerciseId: string;
  lineId: string;
  position: number;
  load: number;
  reps: number;
  rir: number | null;
  warmup: boolean;
  tags: string[];
  outlierStatus: OutlierStatus;
  createdAt: number;
}

export interface LogSetInput {
  /** Pre-generated by the UI per draft so a double tap can never insert the same set twice. */
  id?: string;
  sessionId: string;
  exerciseId: string;
  load: number;
  reps: number;
  rir?: number | null;
  warmup?: boolean;
  tags?: string[];
}

export interface DayExerciseSpec {
  exerciseId: string;
  equipment: ExerciseSpec["equipment"];
  setup: SetupType;
  repMin: number;
  repMax: number;
  /** Exercise name (for the default ceiling by name). */
  name?: string;
  /** The resolved rep ceiling for this lift (per-lift edit, else the default for its kind). Omitted = the engine's default by name. */
  repCeiling?: number;
  isGoalLift: boolean;
  trackEffort: boolean;
  sets: number;
}

type RawSet = {
  id: string;
  session_id: string;
  exercise_id: string;
  line_id: string;
  position: number;
  load: number;
  reps: number;
  rir: number | null;
  is_warmup: number;
  tags_json: string;
  outlier_status: OutlierStatus;
  created_at: number;
};

const toSetRow = (r: RawSet): SetRow => ({
  id: r.id,
  sessionId: r.session_id,
  exerciseId: r.exercise_id,
  lineId: r.line_id,
  position: r.position,
  load: r.load,
  reps: r.reps,
  rir: r.rir,
  warmup: r.is_warmup === 1,
  tags: JSON.parse(r.tags_json) as string[],
  outlierStatus: r.outlier_status,
  createdAt: r.created_at,
});

const toLogged = (r: SetRow): LoggedSet => ({
  load: r.load,
  reps: r.reps,
  rir: r.rir,
  warmup: r.warmup,
  tags: r.tags,
  outlierStatus: r.outlierStatus,
});

export function createWorkoutRepo(db: Db, deps: Deps) {
  const { newId, now } = deps;

  /** Resume the open session for this programme day if there is one, otherwise create it. Never creates a second one. */
  async function startOrResumeSession(dayId: string, gymId: string): Promise<{ id: string; resumed: boolean }> {
    const find = () =>
      db.get<{ id: string; status: string }>(
        "SELECT id, status FROM session WHERE programme_day_id = ? AND status IN ('planned','in_progress') AND deleted_at IS NULL",
        [dayId],
      );
    return db.transaction(async () => {
      const open = await find();
      const t = now();
      if (open) {
        if (open.status === "planned") {
          await db.run("UPDATE session SET status = 'in_progress', started_at = ?, updated_at = ? WHERE id = ?", [t, t, open.id]);
        }
        return { id: open.id, resumed: true };
      }
      const day = await db.get<{ programme_version_id: string }>("SELECT programme_version_id FROM programme_day WHERE id = ? AND deleted_at IS NULL", [dayId]);
      if (!day) throw new Error("Unknown programme day");
      const id = newId();
      await db.run(
        `INSERT INTO session (id, programme_version_id, programme_day_id, gym_id, status, started_at, created_at, updated_at)
         VALUES (?, ?, ?, ?, 'in_progress', ?, ?, ?)`,
        [id, day.programme_version_id, dayId, gymId, t, t, t],
      );
      return { id, resumed: false };
    });
  }

  async function getSession(sessionId: string) {
    return db.get<{ id: string; programme_day_id: string; gym_id: string; status: string; started_at: number | null; finished_at: number | null }>(
      "SELECT id, programme_day_id, gym_id, status, started_at, finished_at FROM session WHERE id = ? AND deleted_at IS NULL",
      [sessionId],
    );
  }

  async function finishSession(sessionId: string): Promise<void> {
    const t = now();
    await db.run("UPDATE session SET status = 'finished', finished_at = ?, updated_at = ? WHERE id = ? AND status = 'in_progress'", [t, t, sessionId]);
  }

  async function getLine(exerciseId: string, gymId: string, setup: SetupType): Promise<{ id: string } | null> {
    return db.get<{ id: string }>(
      "SELECT id FROM exercise_line WHERE exercise_id = ? AND gym_id = ? AND setup = ? AND deleted_at IS NULL",
      [exerciseId, gymId, setup],
    );
  }

  /** A line is created on first use (e.g. a new gym or a new setup starts a separate history stream). */
  async function ensureLine(exerciseId: string, gymId: string, setup: SetupType): Promise<string> {
    const existing = await getLine(exerciseId, gymId, setup);
    if (existing) return existing.id;
    const id = newId();
    const t = now();
    await db.run("INSERT INTO exercise_line (id, exercise_id, gym_id, setup, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?)", [id, exerciseId, gymId, setup, t, t]);
    return id;
  }

  async function listSessionSets(sessionId: string, exerciseId?: string): Promise<SetRow[]> {
    const rows = await db.all<RawSet>(
      `SELECT id, session_id, exercise_id, line_id, position, load, reps, rir, is_warmup, tags_json, outlier_status, created_at
       FROM workout_set WHERE session_id = ? AND deleted_at IS NULL ${exerciseId ? "AND exercise_id = ?" : ""}
       ORDER BY exercise_id, position`,
      exerciseId ? [sessionId, exerciseId] : [sessionId],
    );
    return rows.map(toSetRow);
  }

  /** Finished sessions of one line, oldest first, as engine history. Unconfirmed outliers are kept (the engine ignores them). */
  async function getHistory(line: LineIdentity, lineId: string): Promise<HistorySession[]> {
    const rows = await db.all<RawSet & { sid: string; finished_at: number }>(
      `SELECT ws.*, s.id AS sid, s.finished_at AS finished_at FROM workout_set ws JOIN session s ON s.id = ws.session_id
       WHERE ws.line_id = ? AND s.status = 'finished' AND ws.deleted_at IS NULL AND s.deleted_at IS NULL
       ORDER BY s.finished_at, ws.position`,
      [lineId],
    );
    const bySession = new Map<string, HistorySession>();
    for (const r of rows) {
      let h = bySession.get(r.sid);
      if (!h) {
        h = { line, performedAt: new Date(r.finished_at).toISOString(), sets: [] };
        bySession.set(r.sid, h);
      }
      h.sets.push(toLogged(toSetRow(r)));
    }
    return [...bySession.values()];
  }

  /** The last finished session of this line: what the lifter did last time, for display. */
  async function lastPerformance(line: LineIdentity, lineId: string): Promise<{ performedAt: string; sets: LoggedSet[] } | null> {
    const h = await getHistory(line, lineId);
    const last = h[h.length - 1];
    return last ? { performedAt: last.performedAt, sets: last.sets.filter((s) => !s.warmup) } : null;
  }

  async function loadRejectionMemory(line: LineIdentity, lineId: string): Promise<RejectionMemory> {
    const rows = await db.all<{ jump_kind: string; count: number; last_rejected_at: number }>(
      "SELECT jump_kind, count, last_rejected_at FROM rejection_memory WHERE line_id = ? AND deleted_at IS NULL",
      [lineId],
    );
    const key = lineKey(line);
    return { records: rows.map((r) => ({ lineKey: key, jumpKind: r.jump_kind, count: r.count, lastRejectedAt: new Date(r.last_rejected_at).toISOString() })) };
  }

  /** Engine proposal for one programme exercise from history that exists right now. Not stored (PR5 stores the next session's). */
  async function liveProposal(ex: DayExerciseSpec, gym: GymFingerprint): Promise<{ proposal: Proposal; lineId: string; line: LineIdentity }> {
    const line: LineIdentity = { exerciseId: ex.exerciseId, gymId: gym.gymId, setup: ex.setup };
    const lineId = await ensureLine(ex.exerciseId, gym.gymId, ex.setup);
    const history = await getHistory(line, lineId);
    const rejections = await loadRejectionMemory(line, lineId);
    const proposal = proposeNext({
      exercise: {
        exerciseId: ex.exerciseId,
        name: ex.name,
        equipment: ex.equipment,
        setup: ex.setup,
        repRange: { min: ex.repMin, max: ex.repMax },
        progression: ex.repCeiling !== undefined ? { repCeiling: ex.repCeiling } : undefined,
        isGoalLift: ex.isGoalLift,
        trackEffort: ex.trackEffort,
        plannedSets: ex.sets,
      },
      gym,
      history,
      rejections,
      asOf: new Date(now()).toISOString(),
    });
    return { proposal, lineId, line };
  }

  /**
   * Save a set locally and check it against the recent line. A set far from the line is stored as `unconfirmed`
   * and does not move the next target until the lifter confirms it. Warm-ups are never checked.
   * Idempotent on `id`: a double tap with the same draft id inserts once.
   */
  async function logSet(
    input: LogSetInput,
    ctx: { gym: GymFingerprint; equipment: ExerciseSpec["equipment"]; setup: SetupType },
  ): Promise<{ id: string; created: boolean; outlier: OutlierResult | null }> {
    const id = input.id ?? newId();
    const existing = await db.get<{ id: string }>("SELECT id FROM workout_set WHERE id = ?", [id]);
    if (existing) return { id, created: false, outlier: null };
    const session = await getSession(input.sessionId);
    if (!session) throw new Error("Unknown session");
    if (session.status !== "in_progress") throw new Error("Session is not in progress");
    if (!(input.reps >= 1) || !Number.isFinite(input.load) || input.load < 0) throw new Error("Invalid set");
    const lineId = await ensureLine(input.exerciseId, session.gym_id, ctx.setup);
    const line: LineIdentity = { exerciseId: input.exerciseId, gymId: session.gym_id, setup: ctx.setup };

    let outlier: OutlierResult | null = null;
    if (!input.warmup) {
      const history = await getHistory(line, lineId);
      const todaySets = (await listSessionSets(input.sessionId, input.exerciseId)).map(toLogged);
      if (todaySets.length > 0) history.push({ line, performedAt: new Date(now()).toISOString(), sets: todaySets });
      outlier = checkOutlier(
        { load: input.load, reps: input.reps, rir: input.rir ?? null },
        { line, history, gymSpec: findSpec(ctx.gym, ctx.equipment) },
      );
    }
    const t = now();
    const pos = await db.get<{ p: number | null }>("SELECT MAX(position) AS p FROM workout_set WHERE session_id = ? AND exercise_id = ?", [input.sessionId, input.exerciseId]);
    await db.run(
      `INSERT INTO workout_set (id, session_id, exercise_id, line_id, position, load, reps, rir, is_warmup, tags_json, outlier_status, created_at, updated_at)
       VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
      [id, input.sessionId, input.exerciseId, lineId, (pos?.p ?? 0) + 1, input.load, input.reps, input.rir ?? null, input.warmup ? 1 : 0, JSON.stringify(input.tags ?? []), outlier?.outlierStatus ?? "none", t, t],
    );
    return { id, created: true, outlier };
  }

  /**
   * Log a planned warm-up ladder as warm-up sets. Ids are fixed per session, exercise and step, so a double tap or a
   * retry after a crash adds nothing twice. Warm-ups skip the outlier check and never drive progression.
   */
  async function addWarmups(
    sessionId: string,
    exerciseId: string,
    steps: { load: number; reps: number }[],
    ctx: { gym: GymFingerprint; equipment: ExerciseSpec["equipment"]; setup: SetupType },
  ): Promise<number> {
    let added = 0;
    for (const [i, s] of steps.entries()) {
      const r = await logSet({ id: `${sessionId}:${exerciseId}:wu${i}`, sessionId, exerciseId, load: s.load, reps: s.reps, warmup: true }, ctx);
      if (r.created) added++;
    }
    return added;
  }

  async function setOutlierStatus(setId: string, status: Exclude<OutlierStatus, "none">): Promise<void> {
    const t = now();
    // "rejected" means: not right (typo / wrong plate). It is excluded from every calculation and hidden.
    await db.run("UPDATE workout_set SET outlier_status = ?, updated_at = ?, deleted_at = CASE WHEN ? = 'rejected' THEN ? ELSE deleted_at END WHERE id = ?", [status, t, status, t, setId]);
  }

  async function deleteSet(setId: string): Promise<void> {
    const t = now();
    await db.run("UPDATE workout_set SET deleted_at = ?, updated_at = ? WHERE id = ? AND deleted_at IS NULL", [t, t, setId]);
  }

  return {
    startOrResumeSession,
    getSession,
    finishSession,
    getLine,
    ensureLine,
    listSessionSets,
    getHistory,
    lastPerformance,
    loadRejectionMemory,
    liveProposal,
    logSet,
    addWarmups,
    setOutlierStatus,
    deleteSet,
  };
}
export type WorkoutRepo = ReturnType<typeof createWorkoutRepo>;
